#!/usr/bin/awk -f
BEGIN{
	OFS = "\t"
	FILOGENY_FIELDS = 10
	kind = 1
	domain = 2
	kingdom = 3
	phylum = 4
	class = 5
	order = 6
	family = 7
	genus = 8
	species = 9
	strain = 10
}
{
	known_fields = split($0, filogeny, ";")

	for (i=domain; i <= FILOGENY_FIELDS; i++) {
		printf((filogeny[i] ? filogeny[i] : "*") OFS)
	}
	printf(ORS)
}
